version: '3'
services:
    app:
        container_name: chatplanet_app
        image: node:20.9.0
        ports:
             - "9090:9090"
             - "9091:9091"
             - "3000:3000"
        working_dir: /opt/src
        volumes:
            - ./:/opt/src
        environment:
            - APPENV=${APPENV}
            - HOSTENV=DOCKER
        command: bash -c 'if [ "$APPENV" == "production" ]; then npm run prod; else npm run dev; fi'
    redis:
        container_name: chatplanet_redis
        image: redis:7.2.3
