version: '3'
services:
    app:
        container_name: chatplanet_app
        image: node:20.9.0
        ports:
            - "9000:9000"
            - "9001:9001"
            - "3000:3000"
        volumes:
            - ./:/opt/src
        command: bash -c 'cd /opt/src && if [ "$APPENV" = "production" ]; then npm run setup && npm run prod; else npm run setup && npm run dev; fi'
        environment:
            - APPENV=${APPENV}
            - HOSTENV=DOCKER
    redis:
        container_name: chatplanet_redis
        image: redis:7.2.3